runtime: nodejs16

env_variables:
  DATABASE_URL: 'mysql://0vnendapbmgof2ibrkuc:pscale_pw_oyGpK7peWzR2ys6vDbvjh8YJDexGQx9lbXjlPK37KW3@aws.connect.psdb.cloud/cs5610-final-project?sslaccept=strict'
  AUTH0_JWK_URL: 'https://cs5610-reading-web.us.auth0.com/.well-known/jwks.json'
  AUTH0_AUDIENCE: 'https://api.books'
  AUTH0_ISSUER: 'https://cs5610-reading-web.us.auth0.com'
  PORT: 8080
